{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "mychart.fullname" . }}
spec:
  host: {{ .Values.route.host  }}
  port:
    targetPort: {{ .Values.route.port }}
  to:
    kind: Service
    name: {{ include "mychart.fullname" . }}
{{- end }}
